### PR TITLE
Picostuff test pull request

### PR DESCRIPTION
**Pull request by lurk101**
Just a test.

### CODE REVIEW

**Comment by rtrussell** [comment]
A few comments:

- If we put the example programs in **examples/pico** my release scripts will incorporate them in all the GUI versions as well!
- Anyway, these examples (with the exception of gpio.bbc and blink.bbc) are not Pico-specific.  Perhaps the best place for them would be **console/examples**?
- There shouldn't be anything in **bin/pico** (that's for a GUI edition for the Pico, if we end up with one).
- Why has **console/linux/makefile** been modified (it's got nothing to do with the Pico)?
- Why has **bbasmb_x86_32_TODO.c** been deleted?
- The controversial issue of **align.h**!  I fully understand the reasoning behind adding this file, but as discussed at the forum it would mean me modifying the makefiles and/or project files for all the GUI builds, which would be a lot of work and potentially non-trivial (particularly on Android and iOS).  I know it's not good practice to incorporate the same content in two different header files, but I would very much prefer embedding align.h separately in **BBC.h** and **bbccon.h**.

**Comment by ejolson2005** [comment]
Since align.h is included by BBC.h nothing needs to be changed with any of the build scripts.  In particular, all the console and SDLS2 versions should still build without any changes.  If that's not the case, then there is a bug and I'm sorry.

All the makefiles were missing a make clean rule.  I added one to the linux version for convenience.  Feel free to take it out again.

I didn't know adding the pico directory to the examples folder would affect your build scripts.  Let's move it back to /mcu where it used to be.  Note the build scripts in /mcu/lfstools will also have to be changed.  I think it's a good idea to separate the pico-specific examples from the general ones.

By all means put bbasmb_x86_32_TODO.c back in.  I thought it was you who removed it.

Instead of bin/vga could the VGA version go in console/picovga?

**Comment by lurk101** [comment]
I'll move the makefile back to console/pico. as well as the README I guess.

**Comment by lurk101** [comment]
Richard, you can safely merge this. It will merge into your picostuff branch. Further necessary update can happen in further pull requests.

**Comment by rtrussell** [comment]
> Since align.h is included by BBC.h nothing needs to be changed with any of the build scripts.

I'm using regular **make** (not cmake or anything fancy) and if I don't manually add align.h as a dependency to **every** makefile nothing will get rebuilt if that file is changed.  In the case of the Android and iOS editions align.h won't even be included in the project!

> All the makefiles were missing a make clean rule.

I've never used such a rule.

> I didn't know adding the pico directory to the examples folder would affect your build scripts.

The examples folder has many subdirectories, the only sensible solution is for my release scripts to include them all automatically.

> Let's move it back to /mcu where it used to be.

I didn't ask, but what actually is **/mcu**?  Sorry for my ignorance.

> Instead of bin/vga could the VGA version go in console/picovga?

It's not a console version!

**Comment by lurk101** [comment]
mcu is where most if not all for the pico specific source code, including the imported 3rd party submodules ended up.

**Comment by rtrussell** [comment]
> work around intptr_t undefined for 64 bit builds

I don't know what this means.  **intptr_t** is defined (in stdint.h) always, irrespective of the bit-depth.  It's used extensively in upstream BBC BASIC, in both 32-bit and 64-bit builds.

**Comment by rtrussell** [comment]
> All is well, add missing include to bbmain.c

Upstream bbmain.c already has that include, it's not "missing".  I'm really anxious about merging this pull request for fear that it is going to undo recent changes in upstream.  Shouldn't you have updated the fork first?

**Comment by lurk101** [comment]
That's good to know. I must have been deleted by one of these 2 dozen commits?

My fork is up to date but it was deleted later by
```
 commit bbfee4fc29a49614bd83f369f6c802cebc695e1e
Author: Memotech Bill <64212746+Memotech-Bill@users.noreply.github.com>
Date:   Tue Sep 7 14:43:10 2021 +0100

    Merge changes from Eric's pico-36
```
Don't know why

**Pull request merged**
