### PR TITLE
Add support for x86_64 OpenBSD

### PR DESCRIPTION
**Pull request by ghost**
Hello, to support OpenBSD for console mode edition:
- `console/openbsd/makefile` copied from linux, `gcc` changed to `cc`,  `-ldl -lrt` removed.
- `myThread` handle `read` with `EINTR`.
- Add `StartTimer`, `StopTimer` for OpenBSD with `setitimer`, which is a global timer. But I think it's fine since it seems BBCSDL only use most one at time by `UserTimerID`. 

To support OpenBSD for SDL mode:
- `bin/openbsd/makefile` copied from linux, `gcc` changed to `cc` and `wxneeded` and `origin` added to linker flags.
- `bbcsdl.c` handle the case when `SDL_GetBasePath` returns `NULL` (as on OpenBSD) by `realpath` and `dirname` to `argv[0]`.
- In `bbdata_x86_64.nas` and `bbdata_x86_32.nas`, `random` was remove from GLOBAL, since it confliets with the system C library.

### CODE REVIEW

**Comment by rtrussell** [comment]
Sorry for the lack of feedback on this.  I am unsure of the wisdom of adding a new target platform, especially one which I do not have available here for testing on.   One potential issue is whether OpenBSD differs sufficiently from Linux to need a new value allocated to the `@platform%` enumeration; does the BASIC programmer typically need to know which it is?

**Comment by ghost** [comment]
Hello, thank you for feedback!
I think as long as we only call SDL (the typically way I see) and POSIX APIs instead OS specified APIs in BBCSDL, there is no viewable difference between Linux, OpenBSD and MacOSX.  I set `platform` of OpenBSD to the same with MacOSX since it have a similiar `ls` implementation without support GNU ls options.  `ls` was called in BBCEDIT for display file size.

And I forget to say that the adding `libgen.h` include should be tested on Windows, I only have Linux and OpenBSD.

Also I think it's fine here to not merge this if there is no enough interest for OpenBSD now, maybe other BSDs or OS (one I like is HaikuOS) fans will come here later...

Last, a big thank you for bring BBCSDL into the world which I find so much fun!

**Comment by rtrussell** [comment]
> I think as long as we only call SDL (the typically way I see) and POSIX APIs instead OS specified APIs in BBCSDL, there is no viewable difference between Linux, OpenBSD and MacOSX.

Unfortunately there are some important differences between Linux and MacOS which can affect the BBC BASIC programmer, which is the main reason why they are allocated different values in the @platform% enumeration.  Here are some which come to mind:

- Filenames in MacOS are case-insensitive, in Linux they are case-sensitive.
- The shell command for opening a web browser is different (xdg-open vs open).
- Shared libraries (typically) have a .dylib extension in MacOS and .so in Linux.
- MacOS has 'application bundles' (with a .app extension) whilst Linux doesn't have anything similar.

My main concern about adding an OpenBSD target to my repository is that I would need to be in a position to test each new release on that platform myself, and I don't currently have it available here.

Having sought advice on one of the BBC BASIC forums, their suggestion was that you should maintain the OpenBSD target as a fork, rather than merging the changes into my repository.  Would that be an acceptable approach?

**Comment by ghost** [comment]
> Having sought advice on one of the BBC BASIC forums, their suggestion was that you should maintain the OpenBSD target as a fork, rather than merging the changes into my repository. Would that be an acceptable approach?

Yeah, that's no problem for me, and feel free to close this PR if you see fit, thank you!

**Comment by rtrussell** [comment]
Thanks for your understanding.

**Pull request closed without merging**
